auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: hackersun
url: http://hackersun.github.io/
feed: /atom.xml
author_info: <a href="http://hackersun.github.io/">hackersun</a>
